# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RasidPlugin
                                 A QGIS plugin
 Run cloud-based geospatial analysis and satellite workflows from Rasid. 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-20
        copyright            : (C) 2026 by RASID 
        email                : info@rasid.ai
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'libs'))

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RasidPlugin class from file RasidPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    # Add venv to sys.path if it exists (but don't check/install packages yet)
    # Package installation happens when user clicks the plugin icon (see rasid_plugin.py run() method)
    from .rasid_components.dependencies import venv_manager
    venv_manager.ensure_venv_packages_available()

    from .rasid_plugin import RasidPlugin
    return RasidPlugin(iface)
