# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RasidPlugin
                                 A QGIS plugin
 Run cloud-based geospatial analysis and satellite workflows from Rasid. 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-20
        copyright            : (C) 2026 by RASID 
        email                : info@rasid.ai
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RasidPlugin class from file RasidPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .rasid_plugin import RasidPlugin
    return RasidPlugin(iface)
