# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RasidPlugin
                                 A QGIS plugin
 Run cloud-based geospatial analysis and satellite workflows from Rasid.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-20
        git sha              : $Format:%H$
        copyright            : (C) 2026 by RASID
        email                : info@rasid.ai
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, QThread, pyqtSignal
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

from .resources import *
from .rasid_plugin_dialog import RasidPluginDialog
from .rasid_components.login_dialog import LoginDialog
from .rasid_components.compat import exec_dialog
from .rasid_components.rasid_client import RasidClient
from qgis.PyQt.QtWidgets import QMessageBox, QProgressDialog
import os.path
import keyring


class LoginThread(QThread):
    """Runs login in a background thread so QGIS stays responsive."""
    success = pyqtSignal()
    failed = pyqtSignal(str)

    def __init__(self, client, email, password):
        super().__init__()
        self.client = client
        self.email = email
        self.password = password

    def run(self):
        try:
            self.client.login(self.email, self.password)
            self.success.emit()
        except Exception as e:
            self.failed.emit(str(e))


class RasidPlugin:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'RasidPlugin_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.actions = []
        self.menu = self.tr(u'&Rasid')
        self.first_start = None
        self.client = None
        self.dlg = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        return QCoreApplication.translate('RasidPlugin', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.iface.addWebToolBarIcon(action)

        self.actions.append(action)
        return action

    def initGui(self):
        icon_path = os.path.join(self.plugin_dir, 'icon.png')
        self.add_action(
            icon_path,
            text=self.tr(u'Rasid'),
            callback=self.run,
            parent=self.iface.mainWindow())
        self.first_start = True

    def unload(self):
        for action in self.actions:
            self.iface.removeWebToolBarIcon(action)

    def _show_main_dialog(self):
        """Open the main dialog and load solutions."""
        self.dlg = RasidPluginDialog(self.client, iface=self.iface)
        self.dlg.show_solutions()
        self.dlg.show()
        exec_dialog(self.dlg)

    def _do_login(self, email, password, save_credentials=False):
        """Run login on a background thread with a progress dialog."""
        self.client = RasidClient()

        progress = QProgressDialog("Logging in...", "Cancel", 0, 0, self.iface.mainWindow())
        progress.setWindowTitle("Rasid")
        progress.setCancelButton(None)
        progress.setMinimumDuration(0)
        progress.show()

        self._login_thread = LoginThread(self.client, email, password)
        self._login_success = False
        self._login_save = save_credentials
        self._login_email = email
        self._login_password = password

        def on_success():
            progress.close()
            self._login_success = True
            if self._login_save:
                settings = QSettings()
                settings.setValue("rasid_plugin/email", self._login_email)
                # Store password securely in system keychain
                keyring.set_password("rasid_plugin", self._login_email, self._login_password)
            # Save session cookies for next time
            self.client.save_cookies()
            self._show_main_dialog()

        def on_failed(msg):
            progress.close()
            self.client = None
            if self._login_save:
                # Clear invalid saved credentials
                settings = QSettings()
                email = settings.value("rasid_plugin/email", "")
                if email:
                    try:
                        keyring.delete_password("rasid_plugin", email)
                    except:
                        pass
                settings.remove("rasid_plugin/email")
            QMessageBox.critical(self.iface.mainWindow(), "Login Failed", msg)

        self._login_thread.success.connect(on_success)
        self._login_thread.failed.connect(on_failed)
        self._login_thread.start()

    def run(self):
        # Try to reuse existing session first
        self.client = RasidClient()
        if self.client.load_cookies() and self.client.is_authenticated():
            # Session still valid, skip login!
            self._show_main_dialog()
            return

        # Session invalid or missing - need to login
        settings = QSettings()
        email = settings.value("rasid_plugin/email", "")
        password = None

        if email:
            # Retrieve password from secure keychain
            try:
                password = keyring.get_password("rasid_plugin", email)
            except:
                password = None

        if email and password:
            # Auto-login with saved credentials
            self._do_login(email, password, save_credentials=True)
        else:
            # Show login dialog
            login_dialog = LoginDialog()
            if exec_dialog(login_dialog) != login_dialog.Accepted:
                return
            email = login_dialog.email_input.text()
            password = login_dialog.password_input.text()
            self._do_login(email, password, save_credentials=True)
