# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RasidPlugin
                                 A QGIS plugin
 Run cloud-based geospatial analysis and satellite workflows from Rasid.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-20
        git sha              : $Format:%H$
        copyright            : (C) 2026 by RASID
        email                : info@rasid.ai
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

from .resources import *
from .rasid_plugin_dialog import RasidPluginDialog
from .rasid_components.login_dialog import LoginDialog
from .rasid_components.compat import exec_dialog, QDialog_Accepted
from .rasid_components.rasid_client import RasidClient
from .rasid_components.dependency_installer import DependencyManager
from qgis.PyQt.QtWidgets import QMessageBox
import os.path


class RasidPlugin:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'RasidPlugin_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.actions = []
        self.menu = self.tr(u'&Rasid')
        self.first_start = None
        self.client = None
        self.dlg = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        return QCoreApplication.translate('RasidPlugin', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.iface.addWebToolBarIcon(action)

        self.actions.append(action)
        return action

    def initGui(self):
        icon_path = os.path.join(self.plugin_dir, 'icon.png')
        self.add_action(
            icon_path,
            text=self.tr(u'Rasid'),
            callback=self.run,
            parent=self.iface.mainWindow())
        self.first_start = True

    def unload(self):
        for action in self.actions:
            self.iface.removeWebToolBarIcon(action)

    def _show_main_dialog(self):
        """Open the main dialog and load solutions."""
        self.dlg = RasidPluginDialog(self.client, iface=self.iface)
        self.dlg.show_solutions()
        self.dlg.show()
        exec_dialog(self.dlg)

    def run(self):
        # Check and install dependencies first
        if not DependencyManager.prompt_install(self.iface.mainWindow()):
            QMessageBox.warning(
                self.iface.mainWindow(),
                "Dependencies Required",
                "Required libraries are not installed. The plugin cannot run without them."
            )
            return

        # Initialize client
        self.client = RasidClient()

        # Try to load saved API key first
        if self.client.load_api_key() and self.client.is_authenticated():
            # API key is valid, proceed to main dialog
            self._show_main_dialog()
            return

        # No valid API key - show login dialog
        login_dialog = LoginDialog()
        if exec_dialog(login_dialog) != QDialog_Accepted:
            return

        # Get API key from dialog
        api_key = login_dialog.api_key_input.text().strip()

        if not api_key:
            QMessageBox.warning(self.iface.mainWindow(), "Error", "Please enter an API key")
            return

        # Set and validate API key
        self.client.set_api_key(api_key)

        if self.client.is_authenticated():
            # Save valid API key
            self.client.save_api_key()
            self._show_main_dialog()
        else:
            QMessageBox.critical(self.iface.mainWindow(), "Authentication Failed", "Invalid or revoked API key")
            self.client = None
